### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by savardge** [AndrewReynen/Lazylyst#14]
Hi Andrew, 
I've been looking for a good and flexible package for manually picking arrivals and I liked the flexibility of Lazylyst. However, I'm having issues getting started. I followed the installation instructions (I'm on MacOSX): I created a conda environment (python 2.7) for lazylyst with the requested packages, then ran the python interpreter in the lazylyst directory, but the runLazylyst() module fails to run. Here's the output:

`(lazylyst) C98809:lazylyst genevievesavard$ python
Python 2.7.15 | packaged by conda-forge | (default, Jul  2 2019, 00:42:22)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from lazylyst.Lazylyst import runLazylyst
>>> runLazylyst()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/genevievesavard/anaconda3/envs/lazylyst/lib/python2.7/site-packages/lazylyst/Lazylyst.py", line 1440, in runLazylyst
    window = LazylystMain()
  File "/Users/genevievesavard/anaconda3/envs/lazylyst/lib/python2.7/site-packages/lazylyst/Lazylyst.py", line 44, in __init__
    self.applyPreferences()
  File "/Users/genevievesavard/anaconda3/envs/lazylyst/lib/python2.7/site-packages/lazylyst/Lazylyst.py", line 61, in applyPreferences
    self.pref[key].update(self,init=True)
  File "/Users/genevievesavard/anaconda3/envs/lazylyst/lib/python2.7/site-packages/lazylyst/Preferences.py", line 157, in update
    self.func(init=init)
  File "/Users/genevievesavard/anaconda3/envs/lazylyst/lib/python2.7/site-packages/lazylyst/Lazylyst.py", line 1095, in updateMapProj
    self.updateMapStations(init=init)
  File "/Users/genevievesavard/anaconda3/envs/lazylyst/lib/python2.7/site-packages/lazylyst/Lazylyst.py", line 922, in updateMapStations
    self.mapWidget.loadStaLoc(self.hotVar['staLoc'].val,init)
  File "/Users/genevievesavard/anaconda3/envs/lazylyst/lib/python2.7/site-packages/lazylyst/MapWidgets.py", line 252, in loadStaLoc
    staLocProj=self.projFunc(staLoc[:,1:4])
  File "/Users/genevievesavard/anaconda3/envs/lazylyst/lib/python2.7/site-packages/lazylyst/StationMeta.py", line 81, in <lambda>
    mapProj['func']=lambda xyzArr:np.array(pyproj.transform(inProj,outProj,*xyzArr.T)).T
  File "/Users/genevievesavard/anaconda3/envs/lazylyst/lib/python2.7/site-packages/pyproj/transformer.py", line 545, in transform
    ).transform(xx=x, yy=y, zz=z, tt=tt, radians=radians, errcheck=errcheck)
  File "/Users/genevievesavard/anaconda3/envs/lazylyst/lib/python2.7/site-packages/pyproj/transformer.py", line 274, in transform
    errcheck=errcheck,
  File "pyproj/_transformer.pyx", line 151, in pyproj._transformer._Transformer._transform
pyproj.exceptions.ProjError: x,y,z, and time must be same size: (Internal Proj Error: proj_crs_get_sub_crs: Object is not a CompoundCRS)`

Any idea? 

Not sure if you still have time to support this project, but I thought I'd take a chance and ask a question here.

cheers

**Comment by AndrewReynen** [comment]
Hello,

I tried making a new environment and had it running properly, here are the commands I ran on Windows:

conda create -n lazyEnv python=2.7.12
activate lazyEnv
conda install -c conda-forge obspy=1.1.0
conda install pyqtgraph==0.10.0
conda install scandir=1.5
conda install pyproj=1.9.5.1
conda install future
conda install sip
conda install pyqt=5.6
chdir E:\DownloadsArdvark\Lazylyst-master\Lazylyst-master\lazylyst
python Lazylyst.py

**Comment by AndrewReynen** [comment]
I am using conda version 4.4.10

packages in environment at E:\Anaconda2\envs\lazyEnv:
Name                    Version                   Build  Channel

asn1crypto                0.24.0                py27_1003    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports_abc             0.5                        py_1    conda-forge
blas                      1.0                         mkl
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py27_1    conda-forge
cffi                      1.12.3           py27h4d4881a_0    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.5              py27hc64555f_1    conda-forge
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.4.0                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
freetype                  2.10.0               h3bc688b_1    conda-forge
funcsigs                  1.0.2                      py_3    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
future                    0.17.1                py27_1000    conda-forge
futures                   3.3.0                    py27_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       57.1                      vc9_0
idna                      2.8                   py27_1000    conda-forge
intel-openmp              2019.4                      245
ipaddress                 1.0.22                     py_1    conda-forge
jpeg                      8d                        vc9_2
kiwisolver                1.0.1           py27hdc96acc_1002    conda-forge
libblas                   3.8.0                    12_mkl    conda-forge
libcblas                  3.8.0                    12_mkl    conda-forge
libiconv                  1.15              h0c8e037_1005    conda-forge
liblapack                 3.8.0                    12_mkl    conda-forge
libpng                    1.6.37               h7a46e7a_0    conda-forge
libtiff                   4.0.6                     vc9_2
libxml2                   2.9.9                h00b1425_2    conda-forge
libxslt                   1.1.32            h803002f_1004    conda-forge
lxml                      4.4.1            py27h803002f_0    conda-forge
matplotlib                2.2.4                    py27_0    conda-forge
matplotlib-base           2.2.4            py27he27c676_0    conda-forge
mkl                       2019.4                      245
mock                      3.0.5                    py27_0    conda-forge
numpy                     1.16.4           py27h0d21db5_0    conda-forge
obspy                     1.1.0           py27hc997a72_1002    conda-forge
openssl                   1.0.2r               h0c8e037_0    conda-forge
pip                       19.2.2                   py27_0    conda-forge
proj4                     5.2.0             hc56fc5f_1004    conda-forge
pycparser                 2.19                     py27_1    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyproj                    1.9.5.1         py27haf8c3ea_1007    conda-forge
pyqt                      5.6.0           py27h4cbc711_1008    conda-forge
pyqtgraph                 0.10.0                     py_5    conda-forge
pysocks                   1.7.0                    py27_0    conda-forge
python                    2.7.12                        2    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
qt                        5.6.2                     vc9_0
requests                  2.22.0                   py27_1    conda-forge
scandir                   1.5                      py27_1    conda-forge
scipy                     1.2.1            py27h4c3ab11_0
setuptools                41.0.1                   py27_0    conda-forge
singledispatch            3.4.0.3               py27_1000    conda-forge
sip                       4.18.1          py27hc56fc5f_1000    conda-forge
six                       1.12.0                py27_1000    conda-forge
sqlalchemy                1.3.6            py27h0c8e037_0    conda-forge
sqlite                    3.29.0               h0c8e037_0    conda-forge
tornado                   5.1.1           py27h0c8e037_1000    conda-forge
urllib3                   1.25.3                   py27_0    conda-forge
vc                        9                    h7299396_1
vs2008_runtime            9.0.30729.6161                0    conda-forge
wheel                     0.33.4                   py27_0    conda-forge
win_inet_pton             1.1.0                    py27_0    conda-forge
wincertstore              0.2                   py27_1002    conda-forge
zlib                      1.2.11            h2fa13f4_1005    conda-forge
