### ISSUE TITLE
Screenshots to Preview

### ISSUE THREAD

**Issue by samuelchodur** [AndrewReynen/Lazylyst#2]
It would be useful to see some screenshots of your tool so I know whether I want to go through the installation process or not. The Wiki might be a good place for them?

**Comment by lijunzh** [comment]
I agree with @samuelchodur. We should add some example usage of Lazylst so that users are more aware of what it can do.

**Comment by AndrewReynen** [comment]
I've added some screenshots showing Lazylyst's capability in the [Show case](https://github.com/AndrewReynen/Lazylyst/wiki/Show-Case)  . Feel free to state your use case - can see then if this tool would be beneficial for you.
